### ISSUE TITLE
outputs-pull / push

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/ds-cookiecutter#101]
Would it make sense to create an `outputs-pull` / `outputs-push` command in the `Makefile` along the lines of what we already have for inputs? This would be useful if someone wants to work with processed outputs instead of implementing the whole pipeline.

(or perhaps this use-case is addressed via metaflow)

**Comment by bishax** [comment]
It is addressed and needs to be addressed via. Metaflow (or a similar versioned DAG solution) because...

`outputs/` change when we run code (either because the code changes as we iterate on it or sometimes because the code is non-deterministic e.g. running a clustering algorithm on multiple cores) then we can't just push/pull to S3 because if I run some code and push results to S3 then that might overwrite results you just ran and pushed.

In the past we've basically just dealt with this by only storing data/models in S3 for a project that took a long time to run.

This isn't ideal because:
- You either end up overwriting other/old results like I mentioned above OR you end up creating an ad-hoc (bad) versioning system
- Most of your models/data are still local only

But Metaflow pipelines automatically version our data/models in S3 and allow them to be easily fetched.

N.B. Metaflow  does lots of other things for us too, e.g. easily scaling up compute, but we're just talking about `outputs/` here.
