### ISSUE TITLE
Integration with data_getters repo

### ISSUE THREAD

**Issue by beingkk** [nestauk/ds-cookiecutter#68]
Hi, I created a [new repo](https://github.com/nestauk/innovation_sweet_spots) following the [cookiecutter instructions](https://nestauk.github.io/ds-cookiecutter/quickstart/), and then tried to install [data_getters](https://github.com/nestauk/data_getters) repo as I need to access GtR research project data.

Installing `data_getters` results in a lot of warnings and errors (please see [here](https://gist.github.com/beingkk/94c5fee43b0a060a804c84a81a30522c))

This seems to be a python version clash, as the ds-cookiecutter is setup with `python==3.8`, but the `data_getters` installation does work with `python==3.7` 

Please let me know how to best go about this - is it OK to simply use the ds-cookiecutter with python 3.7?

**Comment by bishax** [comment]
Firstly, yes you can use 3.7 - one of the benefits of having a cookiecutter rather than managing things through a framework/library is that they are 'hackable' (perhaps a good thing to have in our docs is what things we deem reasonable to be hacked/customised).

**Comment by bishax** [comment]
I'm going to close this issue because I don't think it is a problem with the cookiecutter. The problem likely relates to the complex dependencies of `data_getters` which pulls in all the dependencies from `nesta` due to our old monolithic architecture.

I've opened #69 to capture the need to better communicate the hackability of the cookiecutter.

**Comment by beingkk** [comment]
Sounds good, thank you very much!
